
package org.occ.p3.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BatchWebService", targetNamespace = "http://webservice.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BatchWebService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.InitResponse")
    @Action(input = "http://webservice.p3.occ.org/BatchWebService/initRequest", output = "http://webservice.p3.occ.org/BatchWebService/initResponse")
    public void init();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "mailMethodOne", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.MailMethodOne")
    @ResponseWrapper(localName = "mailMethodOneResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.MailMethodOneResponse")
    @Action(input = "http://webservice.p3.occ.org/BatchWebService/mailMethodOneRequest", output = "http://webservice.p3.occ.org/BatchWebService/mailMethodOneResponse")
    public void mailMethodOne();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "mailMethodTwo", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.MailMethodTwo")
    @ResponseWrapper(localName = "mailMethodTwoResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.MailMethodTwoResponse")
    @Action(input = "http://webservice.p3.occ.org/BatchWebService/mailMethodTwoRequest", output = "http://webservice.p3.occ.org/BatchWebService/mailMethodTwoResponse")
    public void mailMethodTwo();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "mailMethodThree", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.MailMethodThree")
    @ResponseWrapper(localName = "mailMethodThreeResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.MailMethodThreeResponse")
    @Action(input = "http://webservice.p3.occ.org/BatchWebService/mailMethodThreeRequest", output = "http://webservice.p3.occ.org/BatchWebService/mailMethodThreeResponse")
    public void mailMethodThree(
        @WebParam(name = "arg0", targetNamespace = "")
        Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "send", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.SendResponse")
    @Action(input = "http://webservice.p3.occ.org/BatchWebService/sendRequest", output = "http://webservice.p3.occ.org/BatchWebService/sendResponse")
    public void send(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "send2", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.Send2")
    @ResponseWrapper(localName = "send2Response", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.Send2Response")
    @Action(input = "http://webservice.p3.occ.org/BatchWebService/send2Request", output = "http://webservice.p3.occ.org/BatchWebService/send2Response")
    public void send2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "send1", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.Send1")
    @ResponseWrapper(localName = "send1Response", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.Send1Response")
    @Action(input = "http://webservice.p3.occ.org/BatchWebService/send1Request", output = "http://webservice.p3.occ.org/BatchWebService/send1Response")
    public void send1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
