
package org.occ.p3.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BatchWebServiceWeb", targetNamespace = "http://webservice.p3.occ.org/", wsdlLocation = "http://lfr028236:8080/bibliot-webservice-new/ws/WebServiceBatch?wsdl")
public class BatchWebServiceWeb
    extends Service
{

    private final static URL BATCHWEBSERVICEWEB_WSDL_LOCATION;
    private final static WebServiceException BATCHWEBSERVICEWEB_EXCEPTION;
    private final static QName BATCHWEBSERVICEWEB_QNAME = new QName("http://webservice.p3.occ.org/", "BatchWebServiceWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lfr028236:8080/bibliot-webservice-new/ws/WebServiceBatch?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BATCHWEBSERVICEWEB_WSDL_LOCATION = url;
        BATCHWEBSERVICEWEB_EXCEPTION = e;
    }

    public BatchWebServiceWeb() {
        super(__getWsdlLocation(), BATCHWEBSERVICEWEB_QNAME);
    }

    public BatchWebServiceWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), BATCHWEBSERVICEWEB_QNAME, features);
    }

    public BatchWebServiceWeb(URL wsdlLocation) {
        super(wsdlLocation, BATCHWEBSERVICEWEB_QNAME);
    }

    public BatchWebServiceWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BATCHWEBSERVICEWEB_QNAME, features);
    }

    public BatchWebServiceWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BatchWebServiceWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BatchWebService
     */
    @WebEndpoint(name = "BatchWebServicePort")
    public BatchWebService getBatchWebServicePort() {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "BatchWebServicePort"), BatchWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BatchWebService
     */
    @WebEndpoint(name = "BatchWebServicePort")
    public BatchWebService getBatchWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "BatchWebServicePort"), BatchWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BATCHWEBSERVICEWEB_EXCEPTION!= null) {
            throw BATCHWEBSERVICEWEB_EXCEPTION;
        }
        return BATCHWEBSERVICEWEB_WSDL_LOCATION;
    }

}
