
package org.occ.p3.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BorrowWebService", targetNamespace = "http://webservice.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BorrowWebService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.InitResponse")
    @Action(input = "http://webservice.p3.occ.org/BorrowWebService/initRequest", output = "http://webservice.p3.occ.org/BorrowWebService/initResponse")
    public void init();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borrowBook", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.BorrowBook")
    @ResponseWrapper(localName = "borrowBookResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.BorrowBookResponse")
    @Action(input = "http://webservice.p3.occ.org/BorrowWebService/borrowBookRequest", output = "http://webservice.p3.occ.org/BorrowWebService/borrowBookResponse")
    public Boolean borrowBook(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extendBorrow", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.ExtendBorrow")
    @ResponseWrapper(localName = "extendBorrowResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.ExtendBorrowResponse")
    @Action(input = "http://webservice.p3.occ.org/BorrowWebService/extendBorrowRequest", output = "http://webservice.p3.occ.org/BorrowWebService/extendBorrowResponse")
    public Boolean extendBorrow(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "endBorrow", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.EndBorrow")
    @ResponseWrapper(localName = "endBorrowResponse", targetNamespace = "http://webservice.p3.occ.org/", className = "org.occ.p3.webservice.EndBorrowResponse")
    @Action(input = "http://webservice.p3.occ.org/BorrowWebService/endBorrowRequest", output = "http://webservice.p3.occ.org/BorrowWebService/endBorrowResponse")
    public Boolean endBorrow(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
