
package org.occ.p3.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BorrowWebServiceWeb", targetNamespace = "http://webservice.p3.occ.org/", wsdlLocation = "http://lfr028236:8080/bibliot-webservice-new/ws/BorrowWebService?wsdl")
public class BorrowWebServiceWeb
    extends Service
{

    private final static URL BORROWWEBSERVICEWEB_WSDL_LOCATION;
    private final static WebServiceException BORROWWEBSERVICEWEB_EXCEPTION;
    private final static QName BORROWWEBSERVICEWEB_QNAME = new QName("http://webservice.p3.occ.org/", "BorrowWebServiceWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lfr028236:8080/bibliot-webservice-new/ws/BorrowWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BORROWWEBSERVICEWEB_WSDL_LOCATION = url;
        BORROWWEBSERVICEWEB_EXCEPTION = e;
    }

    public BorrowWebServiceWeb() {
        super(__getWsdlLocation(), BORROWWEBSERVICEWEB_QNAME);
    }

    public BorrowWebServiceWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), BORROWWEBSERVICEWEB_QNAME, features);
    }

    public BorrowWebServiceWeb(URL wsdlLocation) {
        super(wsdlLocation, BORROWWEBSERVICEWEB_QNAME);
    }

    public BorrowWebServiceWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BORROWWEBSERVICEWEB_QNAME, features);
    }

    public BorrowWebServiceWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BorrowWebServiceWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BorrowWebService
     */
    @WebEndpoint(name = "BorrowWebServicePort")
    public BorrowWebService getBorrowWebServicePort() {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "BorrowWebServicePort"), BorrowWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BorrowWebService
     */
    @WebEndpoint(name = "BorrowWebServicePort")
    public BorrowWebService getBorrowWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "BorrowWebServicePort"), BorrowWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BORROWWEBSERVICEWEB_EXCEPTION!= null) {
            throw BORROWWEBSERVICEWEB_EXCEPTION;
        }
        return BORROWWEBSERVICEWEB_WSDL_LOCATION;
    }

}
