
package org.occ.p3.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MemberWebServiceWeb", targetNamespace = "http://webservice.p3.occ.org/", wsdlLocation = "http://lfr028236:8080/bibliot-webservice-new/ws/MemberWebService?wsdl")
public class MemberWebServiceWeb
    extends Service
{

    private final static URL MEMBERWEBSERVICEWEB_WSDL_LOCATION;
    private final static WebServiceException MEMBERWEBSERVICEWEB_EXCEPTION;
    private final static QName MEMBERWEBSERVICEWEB_QNAME = new QName("http://webservice.p3.occ.org/", "MemberWebServiceWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lfr028236:8080/bibliot-webservice-new/ws/MemberWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBERWEBSERVICEWEB_WSDL_LOCATION = url;
        MEMBERWEBSERVICEWEB_EXCEPTION = e;
    }

    public MemberWebServiceWeb() {
        super(__getWsdlLocation(), MEMBERWEBSERVICEWEB_QNAME);
    }

    public MemberWebServiceWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBERWEBSERVICEWEB_QNAME, features);
    }

    public MemberWebServiceWeb(URL wsdlLocation) {
        super(wsdlLocation, MEMBERWEBSERVICEWEB_QNAME);
    }

    public MemberWebServiceWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBERWEBSERVICEWEB_QNAME, features);
    }

    public MemberWebServiceWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberWebServiceWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MemberWebService
     */
    @WebEndpoint(name = "MemberWebServicePort")
    public MemberWebService getMemberWebServicePort() {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "MemberWebServicePort"), MemberWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberWebService
     */
    @WebEndpoint(name = "MemberWebServicePort")
    public MemberWebService getMemberWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "MemberWebServicePort"), MemberWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBERWEBSERVICEWEB_EXCEPTION!= null) {
            throw MEMBERWEBSERVICEWEB_EXCEPTION;
        }
        return MEMBERWEBSERVICEWEB_WSDL_LOCATION;
    }

}
