
package org.occ.p3.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkWebServiceWeb", targetNamespace = "http://webservice.p3.occ.org/", wsdlLocation = "http://lfr028236:8080/bibliot-webservice-new/ws/WorkWebService?wsdl")
public class WorkWebServiceWeb
    extends Service
{

    private final static URL WORKWEBSERVICEWEB_WSDL_LOCATION;
    private final static WebServiceException WORKWEBSERVICEWEB_EXCEPTION;
    private final static QName WORKWEBSERVICEWEB_QNAME = new QName("http://webservice.p3.occ.org/", "WorkWebServiceWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lfr028236:8080/bibliot-webservice-new/ws/WorkWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKWEBSERVICEWEB_WSDL_LOCATION = url;
        WORKWEBSERVICEWEB_EXCEPTION = e;
    }

    public WorkWebServiceWeb() {
        super(__getWsdlLocation(), WORKWEBSERVICEWEB_QNAME);
    }

    public WorkWebServiceWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKWEBSERVICEWEB_QNAME, features);
    }

    public WorkWebServiceWeb(URL wsdlLocation) {
        super(wsdlLocation, WORKWEBSERVICEWEB_QNAME);
    }

    public WorkWebServiceWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKWEBSERVICEWEB_QNAME, features);
    }

    public WorkWebServiceWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkWebServiceWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WorkWebService
     */
    @WebEndpoint(name = "WorkWebServicePort")
    public WorkWebService getWorkWebServicePort() {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "WorkWebServicePort"), WorkWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkWebService
     */
    @WebEndpoint(name = "WorkWebServicePort")
    public WorkWebService getWorkWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.p3.occ.org/", "WorkWebServicePort"), WorkWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WORKWEBSERVICEWEB_EXCEPTION!= null) {
            throw WORKWEBSERVICEWEB_EXCEPTION;
        }
        return WORKWEBSERVICEWEB_WSDL_LOCATION;
    }

}
